# Album: http://imgur.com/a/24ByN
THOTH = [  ["0 - The Fool", "http://i.imgur.com/PQ2nG95.jpg"],
                ["I - The Magus", "http://i.imgur.com/qItZSaz.jpg"],
                ["II - The Priestess", "http://i.imgur.com/joRLHGK.jpg"],
                ["III - The Empress", "http://i.imgur.com/1xiJAUq.jpg"],
                ["IV - The Emperor", "http://i.imgur.com/yVKoH2j.jpg"],
                ["V - The Hierophant", "http://i.imgur.com/8q8wkZv.jpg"],
                ["VI - The Lovers", "http://i.imgur.com/7fBAtUv.jpg"],
                ["VII - The Chariot", "http://i.imgur.com/axTt8o6.jpg"],
                ["VIII - Adjustment", "http://i.imgur.com/jFK0rW9.jpg"],
                ["IX - The Hermit", "http://i.imgur.com/vKjpFv6.jpg"],
                ["X - Fortune", "http://i.imgur.com/SfcEUFi.jpg"],
                ["XI - Lust", "http://i.imgur.com/pybCauK.jpg"],
                ["XII - The Hanged Man", "http://i.imgur.com/NH0vt4j.jpg"],
                ["XIII - Death", "http://i.imgur.com/0RG898u.jpg"],
                ["XIV - Art", "http://i.imgur.com/G91EXFL.jpg"],
                ["XV - The Devil", "http://i.imgur.com/RnRASpz.jpg"],
                ["XVI - The Tower", "http://i.imgur.com/S6Z2f1f.jpg"],
                ["XVII - The Star", "http://i.imgur.com/3yYIGvm.jpg"],
                ["XVIII - The Moon", "http://i.imgur.com/wECfVYO.jpg"],
                ["XIX - The Sun", "http://i.imgur.com/NGwTuoK.jpg"],
                ["XX - The Aeon", "http://i.imgur.com/LhXJy0f.jpg"],
                ["XXI - The Universe", "http://i.imgur.com/HDwUWBF.jpg"],
                ["Ace of Wands", "http://i.imgur.com/UK2efBo.jpg"],
                ["2 of Wands - Dominion", "http://i.imgur.com/fbzFflB.jpg"],
                ["3 of Wands - Virtue", "http://i.imgur.com/DwU6See.jpg"],
                ["4 of Wands - Completion", "http://i.imgur.com/LiMx96X.jpg"],
                ["5 of Wands - Strife", "http://i.imgur.com/rPlrbyT.jpg"],
                ["6 of Wands - Victory", "http://i.imgur.com/YyB5fCr.jpg"],
                ["7 of Wands - Valour", "http://i.imgur.com/nE0HLRN.jpg"],
                ["8 of Wands - Swiftness", "http://i.imgur.com/ChFeclc.jpg"],
                ["9 of Wands - Strength", "http://i.imgur.com/wEod3NT.jpg"],
                ["10 of Wands - Oppression", "http://i.imgur.com/QipWoV0.jpg"],
                ["Princess of Wands", "http://i.imgur.com/XMO3bNF.jpg"],
                ["Prince of Wands", "http://i.imgur.com/mB468fd.jpg"],
                ["Queen of Wands", "http://i.imgur.com/cL17LkX.jpg"],
                ["Knight of Wands", "http://i.imgur.com/sDVt9RW.jpg"],
                ["Ace of Cups", "http://i.imgur.com/qm5f07V.jpg"],
                ["2 of Cups - Love", "http://i.imgur.com/AsweI48.jpg"],
                ["3 of Cups - Abundance", "http://i.imgur.com/wzQVmtq.jpg"],
                ["4 of Cups - Luxury", "http://i.imgur.com/ONZVO0P.jpg"],
                ["5 of Cups - Disappointment", "http://i.imgur.com/xvuIqvn.jpg"],
                ["6 of Cups - Pleasure", "http://i.imgur.com/Od1qfVh.jpg"],
                ["7 of Cups - Debauch", "http://i.imgur.com/h2F7eFh.jpg"],
                ["8 of Cups - Indolence", "http://i.imgur.com/PxdiTDy.jpg"],
                ["9 of Cups - Happiness", "http://i.imgur.com/JLGko7R.jpg"],
                ["10 of Cups - Satiety", "http://i.imgur.com/Wmm2lQL.jpg"],
                ["Princess of Cups", "http://i.imgur.com/BsgXCEO.jpg"],
                ["Prince of Cups", "http://i.imgur.com/CqfClbW.jpg"],
                ["Queen of Cups", "http://i.imgur.com/WdvOb9X.jpg"],
                ["Knight of Cups", "http://i.imgur.com/rbQZuJ0.jpg"],
                ["Ace of Swords", "http://i.imgur.com/nbGXZMt.jpg"],
                ["2 of Swords - Peace", "http://i.imgur.com/kpwBVKZ.jpg"],
                ["3 of Swords - Sorrow", "http://i.imgur.com/0z9d1hY.jpg"],
                ["4 of Swords - Truce", "http://i.imgur.com/9LNCSNC.jpg"],
                ["5 of Swords - Defeat", "http://i.imgur.com/Gub5DXA.jpg"],
                ["6 of Swords - Science", "http://i.imgur.com/etB8X8E.jpg"],
                ["7 of Swords - Futility", "http://i.imgur.com/gk1ivXT.jpg"],
                ["8 of Swords - Interference", "http://i.imgur.com/8eXSUQj.jpg"],
                ["9 of Swords - Cruelty", "http://i.imgur.com/eRQ4XX4.jpg"],
                ["10 of Swords - Ruin", "http://i.imgur.com/6E4h4d4.jpg"],
                ["Princess of Swords", "http://i.imgur.com/tfJ2Uu8.jpg"],
                ["Prince of Swords", "http://i.imgur.com/U8CHSV9.jpg"],
                ["Queen of Swords", "http://i.imgur.com/hb0bjIQ.jpg"],
                ["Knight of Swords", "http://i.imgur.com/YZIa5um.jpg"],
                ["Ace of Disks", "http://i.imgur.com/6FszJp0.jpg"],
                ["2 of Disks - Change", "http://i.imgur.com/TC3Z0dv.jpg"],
                ["3 of Disks - Works", "http://i.imgur.com/ZRYRFoQ.jpg"],
                ["4 of Disks - Power", "http://i.imgur.com/pDi6yuu.jpg"],
                ["5 of Disks - Worry", "http://i.imgur.com/pEtyIqx.jpg"],
                ["6 of Disks - Success", "http://i.imgur.com/M2HXS5A.jpg"],
                ["7 of Disks - Failure", "http://i.imgur.com/ApPSuWl.jpg"],
                ["8 of Disks - Prudence", "http://i.imgur.com/wg2g8gu.jpg"],
                ["9 of Disks - Gain", "http://i.imgur.com/mEAyRq2.jpg"],
                ["10 of Disks - Wealth", "http://i.imgur.com/Z3B5V5E.jpg"],
                ["Princess of Disks", "http://i.imgur.com/i2lye5C.jpg"],
                ["Prince of Disks", "http://i.imgur.com/9CQeGof.jpg"],
                ["Queen of Disks", "http://i.imgur.com/NNi2jMu.jpg"],
                ["Knight of Disks", "http://i.imgur.com/iseQPhE.jpg"]
]


# Album: http://imgur.com/a/zBwe3
RW_DECK = [ ["0 - The Fool", "http://i.imgur.com/xwIpqIC.jpg"],
            ["I - The Magician", "http://i.imgur.com/mxJtSKd.jpg"],
            ["II - The High Priestess", "http://i.imgur.com/d764bKL.jpg"],
            ["III - The Empress", "http://i.imgur.com/BVMYp3Z.jpg"],
            ["IV - The Emperor", "http://i.imgur.com/VxmSea8.jpg"],
            ["V - The Hierophant", "http://i.imgur.com/VbHYvph.jpg"],
            ["VI - The Lovers", "http://i.imgur.com/lwsa3LM.jpg"],
            ["VII - The Chariot", "http://i.imgur.com/LRMtkTi.jpg"],
            ["VIII - Strength", "http://i.imgur.com/rtUPtsZ.jpg"],
            ["IX - The Hermit", "http://i.imgur.com/BJVCRmh.jpg"],
            ["X - Wheel of Fortune", "http://i.imgur.com/TEceoge.jpg"],
            ["XI - Justice", "http://i.imgur.com/xaNM3PW.jpg"],
            ["XII - The Hanged Man", "http://i.imgur.com/XL6jhjQ.jpg"],
            ["XIII - Death", "http://i.imgur.com/vN8frAu.jpg"],
            ["XIV - Temperance", "http://i.imgur.com/b1g6FlS.jpg"],
            ["XV - The Devil", "http://i.imgur.com/ppC8WVB.jpg"],
            ["XVI - The Tower", "http://i.imgur.com/aBv2lbO.jpg"],
            ["XVII - The Star", "http://i.imgur.com/S3WZmhm.jpg"],
            ["XVIII - The Moon", "http://i.imgur.com/oZtqyCr.jpg"],
            ["XIX - The Sun", "http://i.imgur.com/dalzqXX.jpg"],
            ["XX - Judgement", "http://i.imgur.com/1DrOwqp.jpg"],
            ["XXI - The World", "http://i.imgur.com/aRGuRFG.jpg"],
            ["Ace of Wands", "http://i.imgur.com/DabavYD.jpg"],
            ["2 of Wands", "http://i.imgur.com/BMU6WWF.jpg"],
            ["3 of Wands", "http://i.imgur.com/GLj7gSc.jpg"],
            ["4 of Wands", "http://i.imgur.com/UPqeaU3.jpg"],
            ["5 of Wands", "http://i.imgur.com/8bayVFQ.jpg"],
            ["6 of Wands", "http://i.imgur.com/y2PDGpt.jpg"],
            ["7 of Wands", "http://i.imgur.com/vEbIZC5.jpg"],
            ["8 of Wands", "http://i.imgur.com/63Gs9p7.jpg"],
            ["9 of Wands", "http://i.imgur.com/DK5D6WT.jpg"],
            ["10 of Wands", "http://i.imgur.com/BFKf1UI.jpg"],
            ["King of Wands", "http://i.imgur.com/TC4ulvh.jpg"],
            ["Queen of Wands", "http://i.imgur.com/qW1mEme.jpg"],
            ["Knight of Wands", "http://i.imgur.com/e6KDbgR.jpg"],
            ["Page of Wands", "http://i.imgur.com/Yd2jSck.jpg"],
            ["Ace of Cups", "http://i.imgur.com/C7tqudR.jpg"],
            ["2 of Cups", "http://i.imgur.com/lRYMKvv.jpg"],
            ["3 of Cups", "http://i.imgur.com/k3OOClg.jpg"],
            ["4 of Cups", "http://i.imgur.com/5a9PJMq.jpg"],
            ["5 of Cups", "http://i.imgur.com/CCqnB7K.jpg"],
            ["6 of Cups", "http://i.imgur.com/6EYsVJI.jpg"],
            ["7 of Cups", "http://i.imgur.com/eKoqpps.jpg"],
            ["8 of Cups", "http://i.imgur.com/e4Ga7nE.jpg"],
            ["9 of Cups", "http://i.imgur.com/l4Ws2gO.jpg"],
            ["10 of Cups", "http://i.imgur.com/dCgX4Ia.jpg"],
            ["King of Cups", "http://i.imgur.com/kva3dt9.jpg"],
            ["Queen of Cups", "http://i.imgur.com/kJtgSAQ.jpg"],
            ["Knight of Cups", "http://i.imgur.com/uqqqLUq.jpg"],
            ["Page of Cups", "http://i.imgur.com/UUR02Qn.jpg"],
            ["Ace of Swords", "http://i.imgur.com/WnHJVUz.jpg"],
            ["2 of Swords", "http://i.imgur.com/hbeuU1m.jpg"],
            ["3 of Swords", "http://i.imgur.com/Ut69sBV.jpg"],
            ["4 of Swords", "http://i.imgur.com/2jHpfqL.jpg"],
            ["5 of Swords", "http://i.imgur.com/iWeFBUh.jpg"],
            ["6 of Swords", "http://i.imgur.com/nGvrP0t.jpg"],
            ["7 of Swords", "http://i.imgur.com/wOHMCCj.jpg"],
            ["8 of Swords", "http://i.imgur.com/EvRHCRT.jpg"],
            ["9 of Swords", "http://i.imgur.com/XBpVh02.jpg"],
            ["10 of Swords", "http://i.imgur.com/zv74MLW.jpg"],
            ["King of Swords", "http://i.imgur.com/OqVhsfE.jpg"],
            ["Queen of Swords", "http://i.imgur.com/6ztXVin.jpg"],
            ["Knight of Swords", "http://i.imgur.com/sJfwrdN.jpg"],
            ["Page of Swords", "http://i.imgur.com/qO0XgXa.jpg"],
            ["Ace of Pentacles", "http://i.imgur.com/3mglLg1.jpg"],
            ["2 of Pentacles", "http://i.imgur.com/RQORVBu.jpg"],
            ["3 of Pentacles", "http://i.imgur.com/ubGCBP8.jpg"],
            ["4 of Pentacles", "http://i.imgur.com/rx0nXma.jpg"],
            ["5 of Pentacles", "http://i.imgur.com/SxOpbH1.jpg"],
            ["6 of Pentacles", "http://i.imgur.com/izANDOZ.jpg"],
            ["7 of Pentacles", "http://i.imgur.com/Y180oId.jpg"],
            ["8 of Pentacles", "http://i.imgur.com/AikIqPX.jpg"],
            ["9 of Pentacles", "http://i.imgur.com/aadANyr.jpg"],
            ["10 of Pentacles", "http://i.imgur.com/5W91m6C.jpg"],
            ["King of Pentacles", "http://i.imgur.com/In9i1FZ.jpg"],
            ["Queen of Pentacles", "http://i.imgur.com/55RpqQY.jpg"],
            ["Knight of Pentacles", "http://i.imgur.com/p1291Jn.jpg"],
            ["Page of Pentacles", "http://i.imgur.com/xxPXOML.jpg"]
]

# Album: https://imgur.com/a/9N1NX
HAINDL = [ ["0 - The Fool: Act impulsively, follow your feelings, surprise, wonder, excitement, take opportunities that arise.", "https://i.imgur.com/rn87y8T.jpg"],
                ["I - The Magician: Power, Strength, Being in control of one's life. Transforming old situations, bringing in new ones. A burst of energy, creativity, focused will.", "https://i.imgur.com/CgkGRCJ.jpg"],
                ["II - The High Priestess: A time for quiet, for looking inward. Seek peace. Use intuition and feeling. Peace and joy. Possibly, a lover who needs solitude or is avoiding commitment.", "https://i.imgur.com/N7xN0Ne.jpg"],
                ["III - The Empress: Passion, Love of nature, Motherhood. Joyous Activity.", "https://i.imgur.com/gBWJgns.jpg"],
                ["IV - The Emperor: Influence of Society, law. Resurgence of energy. Sexual potency. Arrogance. Insensitivity. Energy and Desire.", "https://i.imgur.com/6K4M84N.jpg"],
                ["V - The Hierophant: Tradition, community and teachings. Conformity. Marriage, or any solemn commitment.", "https://i.imgur.com/bjZfSuZ.jpg"],
                ["VI - The Lovers: The importance of love. Depending on the place in the spread, the state of a specific relationship.", "https://i.imgur.com/ZT80ToP.jpg"],
                ["VII - The Chariot: Willpower in dealing with problems. Will to continue. Deep fear driving a person. Triumph over fear.", "https://i.imgur.com/YZPxh1B.jpg"],
                ["VIII - Strength: Inner strength. Love and gentleness. Confidence. Ability to give love.", "https://i.imgur.com/4T5y2KK.jpg"],
                ["IX - The Hermit: Withdrawal from outside interests. Self-reliance. Self-creation. Developing one's personality. Gaining wisdom. Powerful dreams.", "https://i.imgur.com/GoEAQnA.jpg"],
                ["X - The Wheel of Fortune: Change of circumstances. Taking hold of one's life. Grabbing hold of fate. Time to take what life has given you.", "https://i.imgur.com/AjAMCfE.jpg"],
                ["XI - Justice: Examine your life, weigh things in the balance. A relationship is going badly. Analysis. Take a balanced view.", "https://i.imgur.com/SRdYekZ.jpg"],
                ["XII - The Hanged Man: Attachment. Deep spiritual awareness. Independence.", "https://i.imgur.com/qbqzTzp.jpg"],
                ["XIII - Death: Rarely refers to physical death. More about ideas about death. Psychologically, letting go. New opportunities.", "https://i.imgur.com/OKtSk7R.jpg"],
                ["XIV - Alchemy: Measurement and combination. Do not allow setbacks to turn enthusiasm into its mirror image of dejection. Take control. Moderation.", "https://i.imgur.com/m0J2LMA.jpg"],
                ["XV - The Devil: Something exciting, possibly dangerous or forbidden. Temptation. Physical gratification. Exploring darker feelings. Wild action opens up new areas in life.", "https://i.imgur.com/021O0NW.jpg"],
                ["XVI - The Tower: Long-standing activity or approach that may bring about disaster if continued. Pressure building up. Long-buried emotions let loose. News. A flash of understanding.", "https://i.imgur.com/4VzZ2QT.jpg"],
                ["XVII - The Star: Renewal. Reality and feeling. Cleansing. Humility. Hope.", "https://i.imgur.com/KyvLjn4.jpg"],
                ["XVIII - The Moon: Imagination. Fantasies, daydreams, strong dreams. The sources of creativity.", "https://i.imgur.com/Ggs1lut.jpg"],
                ["XIX - The Sun: Joy and simplicity. Life is wonderful. Energy. Activity, excitement, optimism. Rational approach. Confidence. Sexual Desire.", "https://i.imgur.com/o1hIk7J.jpg"],
                ["XX - Aeon: Renewal. Optimism, in spite of a painful period of change. Change. Spontaneity. All things are possible. Old world seen through new eyes.", "https://i.imgur.com/zBzSbQ4.jpg"],
                ["XXI - The Universe: Success. Becoming happier, more fulfilled. Recovery from illness. An exciting future. Stagnation. Lack of willpower and confidence.", "https://i.imgur.com/ZeZ9ErA.jpg"],
                ["Ace of Wands in the East: Gift of fire. Energy, optimism, confidence. Desire. Beginnings.", "https://i.imgur.com/pED3d7u.jpg"],
                ["2 of Wands - Dominion: Power, Strong Will. The power of spiritual truth.", "https://i.imgur.com/SDZkjlr.jpg"],
                ["3 of Wands - Virtue: Acting in harmony with nature. Purpose. Good fortune.", "https://i.imgur.com/JvnWdMz.jpg"],
                ["4 of Wands - Perfection: New life. Take action at the right moment. Excitement and growth.", "https://i.imgur.com/tEyXLKX.jpg"],
                ["5 of Wands - Conflict: Strife and battle, without hatred or bitterness. Avoidance.", "https://i.imgur.com/BsQuhbQ.jpg"],
                ["6 of Wands - Victory: Triumph. Confidence and firm action will lead to triumph. Inspiration.", "https://i.imgur.com/mAxRj85.jpg"],
                ["7 of Wands - Courage: Courage and daring - possibly, the courage to retreat. Using one's power for transformation.", "https://i.imgur.com/1eQekIy.jpg"],
                ["8 of Wands - Swiftness: Definite movement. Progress. A worthy goal. Finding direction in life. Development of a new love affair.", "https://i.imgur.com/0ujo3tJ.jpg"],
                ["9 of Wands - Power: Great energy. Arrogance, especially toward those who feel weak. Life's resiliency.", "https://i.imgur.com/Ir6ivGA.jpg"],
                ["10 of Wands - Oppression: Oppression. Depression. Transformation from cruelty to liberation. Possible fall.", "https://i.imgur.com/6pYZ8m6.jpg"],
                ["Daughter of Wands in the East (Radha): Abundance. Joy. Good Sense. Culture.", "https://i.imgur.com/SxZHqLW.jpg"],
                ["Son of Wands in the East (Krishna): Love of life. Interest in the arts. Trickster. Attractiveness.", "https://i.imgur.com/WHim8nA.jpg"],
                ["Mother of Wands in the East (Kali): A wild, female energy. Dark power, sexual energy.", "https://i.imgur.com/gN7hetO.jpg"],
                ["Father of Wands in the East (Brahma): A calm person, possibly stuffy. A rooted quality that gives strength.", "https://i.imgur.com/cwBsWYL.jpg"],
                ["Ace of Cups in the North: Happiness. Love, joy, optimism. Love flowing openly between two people.", "https://i.imgur.com/9jtWGFS.jpg"],
                ["2 of Cups - Love: Relationship. Possibly, the need to make a commitment.", "https://i.imgur.com/VQAsocl.jpg"],
                ["3 of Cups - Overflowing: Great feeling. Extreme joy that can turn to tears.", "https://i.imgur.com/GJFcQxY.jpg"],
                ["4 of Cups - Mixed Happiness: Find a moment of peace and balance. Action is possible and will lead to growth.", "https://i.imgur.com/jS2mAIY.jpg"],
                ["5 of Cups - Disappointment: Be patient. Confusion and disappointment are exaggerated.", "https://i.imgur.com/IikREal.jpg"],
                ["6 of Cups - Happiness: Happiness. Loving and being loved. Balance and peace.", "https://i.imgur.com/7Z1tttO.jpg"],
                ["7 of Cups - Illusions of Success: Beware of arrogance and complacency. Fantasies.", "https://i.imgur.com/CG2a56P.jpg"],
                ["8 of Cups - Failure: Failure. Arrogance and greed. Accept help from others.", "https://i.imgur.com/tav40CI.jpg"],
                ["9 of Cups - Fortune: Fortune. Wealth. Emotional breakthrough. Generosity.", "https://i.imgur.com/GUakie5.jpg"],
                ["10 of Cups - Success: Successful development, with some effort required.", "https://i.imgur.com/KKL11QX.jpg"],
                ["Daughter of Cups in the North (Brigid): Calmness and radiance. Peacefulness, and strength of power.", "https://i.imgur.com/a2DBdIj.jpg"],
                ["Son of Cups in the North (Parsival): Sweet-tempered, but naive person. A good heart. A test.", "https://i.imgur.com/2TpT32v.jpg"],
                ["Mother of Cups in the North (Venus of Willendorf): Earthy, Plain, Honest person. Matriarch. Ancient Forces.", "https://i.imgur.com/6rBeZY9.jpg"],
                ["Father of Cups in the North (Odin): A powerful, domineering person. Intelligence. Creativity. Generous and Loving.", "https://i.imgur.com/Z32c6nz.jpg"],
                ["Ace of Swords in the South: Intelligence. Clear thinking. Powerful personality or emotions.", "https://i.imgur.com/ZBiQRuW.jpg"],
                ["2 of Swords - Peace: Tranquility. Opportunity for prospering.", "https://i.imgur.com/EgSKSzo.jpg"],
                ["3 of Swords - Mourning: Oppressive situations. Mourning. Sorrow.", "https://i.imgur.com/0ElHuUM.jpg"],
                ["4 of Swords - Truce: A moment of calm.", "https://i.imgur.com/givY8Ij.jpg"],
                ["5 of Swords - Defeat: An overwhelming situation. Need to hold onto principles until the time comes to make a change.", "https://i.imgur.com/M3H2yYc.jpg"],
                ["6 of Swords - Science: Need for objectivity and honesty.", "https://i.imgur.com/usGUcKv.jpg"],
                ["7 of Swords - Uselessness: Depression. Possibly, the need to leave a situation for new possibilities.", "https://i.imgur.com/MIyrO9k.jpg"],
                ["8 of Swords - Interference: Interference. Gossip. Help or Advice.", "https://i.imgur.com/KMA9UkD.jpg"],
                ["9 of Swords - Cruelty: Cruelty. Feeling like a victim.", "https://i.imgur.com/r92A90N.jpg"],
                ["10 of Swords - Ruin: Pain, confusion. Personal difficulties. Problems.", "https://i.imgur.com/UlK1Unb.jpg"],
                ["Daughter of Swords in the South (Isis): A powerful figure, confident and dynamic.", "https://i.imgur.com/HJFUB8G.jpg"],
                ["Son of Swords in the South (Osiris): Someone gentle yet persuasive. An initiate into esoteric mysteries. Kindness.", "https://i.imgur.com/JNEeHYb.jpg"],
                ["Mother of Swords in the South (Nut): A mysterious person. Devotion. Autonomy.", "https://i.imgur.com/RFjV2lv.jpg"],
                ["Father of Swords in the South (Ra): Dominant, autocratic person. Delegating authority to others. Strong, creative intellect. Fairness.", "https://i.imgur.com/fs59ESw.jpg"],
                ["Ace of Stones in the West: Health. Prosperity. Beauty. Good weather.", "https://i.imgur.com/5REnXiR.jpg"],
                ["2 of Stones - Harmony: Harmonic situations.", "https://i.imgur.com/j9zq682.jpg"],
                ["3 of Stones - Work: Work. Satisfaction.", "https://i.imgur.com/Xz1rRaq.jpg"],
                ["4 of Stones - The Power of the Earth: Creativity and new ideas. Overwhelming energy.", "https://i.imgur.com/QMNLjgB.jpg"],
                ["5 of Stones - Material Difficulty: Wintry time. Money troubles. Illness. Isolation.", "https://i.imgur.com/eLWUblZ.jpg"],
                ["6 of Stones - Success: Great success and joy, possibly short-lived. Find inner truth and happiness.", "https://i.imgur.com/IlflJk6.jpg"],
                ["7 of Stones - Failure: Disharmony. Without careful redirection, failure is possible.", "https://i.imgur.com/8pwMQiw.jpg"],
                ["8 of Stones - Knowledge: Be careful and moderate. Avoid excessive action.", "https://i.imgur.com/jbfgtL5.jpg"],
                ["9 of Stones - Material Gain: Fortune. Money, security, health, comfort. Avoid complacency, greed or conceit.", "https://i.imgur.com/hfXm2vO.jpg"],
                ["10 of Stones - Richness: Good life. Health. A sense of solid reality.", "https://i.imgur.com/lVl7FSg.jpg"],
                ["Daughter of Stones in the West (White Buffalo Woman): Willingness to take responsibility for something greater than oneself. Love, courage, and dedication. Inner beauty.", "https://i.imgur.com/kjNozqz.jpg"],
                ["Son of Stones in the West (Chief Seattle): Taking action to make positive change - with the benefit of the next seven generations in mind.", "https://i.imgur.com/EjnAIew.jpg"],
                ["Mother of Stones in the West (Spider Woman): Serene, probably older woman. Self-confidence.", "https://i.imgur.com/BInYnhc.jpg"],
                ["Father of Stones in the West (Old Man): Fundamental male principle. Someone who cares deeply for family and for nature. Hard Worker.", "https://i.imgur.com/2yTSrl1.jpg"],
			          ["[REVERSED] 0 - The Fool: Difficulty believing in your instincts, fear of stepping into the unknown, do not be reckless.", "https://i.imgur.com/VDlMNqF.jpg"],
                ["[REVERSED] I - The Magician: Natural expression of energy blocked. Inner resistance. Arrogance. Misuse of personal power.", "https://i.imgur.com/Nn26nws.jpg"],
                ["[REVERSED] II - The High Priestess: A time for action, for involvements with others. Commitment in romance.", "https://i.imgur.com/JAYpLYN.jpg"],
                ["[REVERSED] III - The Empress: Passion blocked. Difficulty expressing oneself. Problems with one's mother.", "https://i.imgur.com/EtDpWTx.jpg"],
                ["[REVERSED] IV - The Emperor: Blocked possibility. Development of sensitivity.", "https://i.imgur.com/iSEOHFO.jpg"],
                ["[REVERSED] V - The Hierophant: Social pressure. Doctrines and ideas that have lost meaning. Originality. Gullibility.", "https://i.imgur.com/jQCmjVo.jpg"],
                ["[REVERSED] VI - The Lovers: A relationship ending, trouble in a relationship. Lack of love. Insecurity, loneliness. Loss of Balance.", "https://i.imgur.com/67d3hhf.jpg"],
                ["[REVERSED] VII - The Chariot: Lack of will. Passivity or weakness. It may be best to let things run their course.", "https://i.imgur.com/aRAKoPt.jpg"],
                ["[REVERSED] VIII - Strength: Feeling blocked from one's power. Weak. Overwhelmed. Meditation or some form of relaxation may help restore strength.", "https://i.imgur.com/3AEre1U.jpg"],
                ["[REVERSED] IX - The Hermit: Involvement with others. Fear of loneliness. Disturbing dreams. A desire to not grow up.", "https://i.imgur.com/AIz4ufD.jpg"],
                ["[REVERSED] X - The Wheel of Fortune: Difficulty adjusting to changes. Resistance to change.", "https://i.imgur.com/mBPjqmy.jpg"],
                ["[REVERSED] XI - Justice: Do not act out of habit. Imbalance. You may be acting unfairly. Trying to avoid an honest evaluation.", "https://i.imgur.com/Td5niTi.jpg"],
                ["[REVERSED] XII - The Hanged Man: Being overly influenced by outside ideas. Pressure to conform. Demands. Sacrificing something to get past hangups. Lack of purpose.", "https://i.imgur.com/O7OejE1.jpg"],
                ["[REVERSED] XIII - Death: Resisting change. Stagnation. Inertia. Pain of giving something up.", "https://i.imgur.com/BqDGsva.jpg"],
                ["[REVERSED] XIV - Alchemy: Going to extremes. Excessive behavior. Conserve energy. A person out of control.", "https://i.imgur.com/NvAdoAL.jpg"],
                ["[REVERSED] XV - The Devil: Resisting temptations. Not a time for sensuality. Fear of one's own decisions.", "https://i.imgur.com/2UL5vuV.jpg"],
                ["[REVERSED] XVI - The Tower: Similar to upright meanings, but less severe. A shaking up. A minor disturbance.", "https://i.imgur.com/BI01QSH.jpg"],
                ["[REVERSED] XVII - The Star: Fears for the future. Isolation. Tension or anxiety. Hope.", "https://i.imgur.com/o06VXFt.jpg"],
                ["[REVERSED] XVIII - The Moon: The time to return to \"solar\", rational activities. Conscious mind blocking the unconscious.", "https://i.imgur.com/S9yTtIp.jpg"],
                ["[REVERSED] XIX - The Sun: Sun is clouded over. Day-to-day problems, though happiness remains. Loss of confidence. Frustration.", "https://i.imgur.com/6f0RNSW.jpg"],
                ["[REVERSED] XX - Aeon: Rebirth. Resisting change. A new life, possibly not acknowledged.", "https://i.imgur.com/IPolqSy.jpg"],
                ["[REVERSED] XXI - The Universe: Stagnation. Lack of willpower and confidence. Self-defined limitations. Resistance or opposition.", "https://i.imgur.com/FUIDbum.jpg"],
                ["[REVERSED] Ace of Wands in the East: Lack of focus. Scattered or confused efforts. Pessimism.", "https://i.imgur.com/6GAdNrF.jpg"],
                ["[REVERSED] 2 of Wands - Dominion: Voluntarily giving up a position of power. Seeking adventures. Misuse of power.", "https://i.imgur.com/VaOQ7Fn.jpg"],
                ["[REVERSED] 3 of Wands - Virtue: Being out of harmony with the situation. Difficulty in finding the point of life or in discovering worthy goals.", "https://i.imgur.com/8GVCHTT.jpg"],
                ["[REVERSED] 4 of Wands - Perfection: Errors. Impatient for new start. Wait for genuine opportunity.", "https://i.imgur.com/Gaox8e4.jpg"],
                ["[REVERSED] 5 of Wands - Conflict: Personal and aggressive conflicts. Bitterness towards others.", "https://i.imgur.com/7jutNFt.jpg"],
                ["[REVERSED] 6 of Wands - Victory: Loss of belief. Negative attitude can lead to failure.", "https://i.imgur.com/XiyZkl1.jpg"],
                ["[REVERSED] 7 of Wands - Courage: Loss of nerve. Hesitation. Seek an alternative, possibly reconciliation.", "https://i.imgur.com/0moPw1G.jpg"],
                ["[REVERSED] 8 of Wands - Swiftness: Scattered energy. Contradictory activities. Fear of taking action. Shyness, or jealousy.", "https://i.imgur.com/1UuxFzT.jpg"],
                ["[REVERSED] 9 of Wands - Power: GWeakness. Passivity. Arrogance or misuse of power.", "https://i.imgur.com/Tg0JW97.jpg"],
                ["[REVERSED] 10 of Wands - Oppression: Emerging from a bad situation. Wisdom gained through adversity.", "https://i.imgur.com/FMYImLg.jpg"],
                ["[REVERSED] Daughter of Wands in the East (Radha): Unfulfilled potential.", "https://i.imgur.com/6zRWit0.jpg"],
                ["[REVERSED] Son of Wands in the East (Krishna): Difficulty. Conflict. Problems may bring out depths in a person.", "https://i.imgur.com/axQ8WTm.jpg"],
                ["[REVERSED] Mother of Wands in the East (Kali): Kali-like energy suppressed. Destructiveness outweighs love and joy.", "https://i.imgur.com/co3T3io.jpg"],
                ["[REVERSED] Father of Wands in the East (Brahma): Snobbishness, especially intellectual. Devotion. Doubts, weakness, confusion.", "https://i.imgur.com/DTM4K9M.jpg"],
                ["[REVERSED] Ace of Cups in the North: Happiness is blocked. Trouble communicating. Value of life questioned.", "https://i.imgur.com/RRavY1L.jpg"],
                ["[REVERSED] 2 of Cups - Love: Quarreling or jealousy. Uncertain future. Lack of commitment.", "https://i.imgur.com/Pzzx6rI.jpg"],
                ["[REVERSED] 3 of Cups - Overflowing: Feelings dammed up. Instability.", "https://i.imgur.com/dYUZ5S9.jpg"],
                ["[REVERSED] 4 of Cups - Mixed Happiness: Loss of balance. Suppressed emotions.", "https://i.imgur.com/HnOMuiO.jpg"],
                ["[REVERSED] 5 of Cups - Disappointment: Coming out of disappointment. A realistic view of the past.", "https://i.imgur.com/yWu6gXS.jpg"],
                ["[REVERSED] 6 of Cups - Happiness: The happy moment may be passing. Not recognizing happiness. Unbalanced or excessive behavior.", "https://i.imgur.com/4Q4YwJl.jpg"],
                ["[REVERSED] 7 of Cups - Illusions of Success: Hidden problems emerging. More realistic outlook.", "https://i.imgur.com/hbsf5l6.jpg"],
                ["[REVERSED] 8 of Cups - Failure: Hidden joy. New happiness. Positive change.", "https://i.imgur.com/z3JIS7l.jpg"],
                ["[REVERSED] 9 of Cups - Fortune: Stinginess. Loss.", "https://i.imgur.com/2fMM9Gh.jpg"],
                ["[REVERSED] 10 of Cups - Success: Success Blocked. Negativity, apathy.", "https://i.imgur.com/Qkh01Fa.jpg"],
                ["[REVERSED] Daughter of Cups in the North (Brigid): Loss of self-assurance. Importance of personal history ignored.", "https://i.imgur.com/fSTDv0V.jpg"],
                ["[REVERSED] Son of Cups in the North (Parsival): Avoiding responsibility. Callousness.", "https://i.imgur.com/JgFyhX4.jpg"],
                ["[REVERSED] Mother of Cups in the North (Venus of Willendorf): Someone out of touch with physical realities.", "https://i.imgur.com/jcPwyWs.jpg"],
                ["[REVERSED] Father of Cups in the North (Odin): Father's power disrupted.", "https://i.imgur.com/ByblDMA.jpg"],
                ["[REVERSED] Ace of Swords in the South: Anger. Aggression. Distorted thinking.", "https://i.imgur.com/ZuLcwEK.jpg"],
                ["[REVERSED] 2 of Swords - Peace: Disruption. Seek tranquility within.", "https://i.imgur.com/y4MI5Sa.jpg"],
                ["[REVERSED] 3 of Swords - Mourning: Difficulty accepting loss. The natural cycle will bring renewal.", "https://i.imgur.com/dhsvQop.jpg"],
                ["[REVERSED] 4 of Swords - Truce: Movement away from silence and peace. New beginnings or old troubles.", "https://i.imgur.com/g9yAznU.jpg"],
                ["[REVERSED] 5 of Swords - Defeat: Situation growing better, with courage and persistence.", "https://i.imgur.com/xppcA4J.jpg"],
                ["[REVERSED] 6 of Swords - Science: Idealism used for selfish ends.", "https://i.imgur.com/shS2u5a.jpg"],
                ["[REVERSED] 7 of Swords - Uselessness: Attempting to deal with feelings of uselessness.", "https://i.imgur.com/yRDNxTa.jpg"],
                ["[REVERSED] 8 of Swords - Interference: No interference. Avoiding responsibility.", "https://i.imgur.com/zAyVgRY.jpg"],
                ["[REVERSED] 9 of Swords - Cruelty: Relief from cruel conditions. Confusion. Manipulation.", "https://i.imgur.com/t6dcBqz.jpg"],
                ["[REVERSED] 10 of Swords - Ruin: Troubles passing. Relief. Need to rest.", "https://i.imgur.com/Yo69deC.jpg"],
                ["[REVERSED] Daughter of Swords in the South (Isis): Loss of confidence. Depression.", "https://i.imgur.com/lVPDHqV.jpg"],
                ["[REVERSED] Son of Swords in the South (Osiris): Weakness, possibly corruption.", "https://i.imgur.com/PRmLuxc.jpg"],
                ["[REVERSED] Mother of Swords in the South (Nut): Need for privacy exaggerated. Conflict between love of solitude and love for others.", "https://i.imgur.com/hdpNRtp.jpg"],
                ["[REVERSED] Father of Swords in the South (Ra): Tyrant. A person jealous of personal powerful.", "https://i.imgur.com/0rh5xYH.jpg"],
                ["[REVERSED] Ace of Stones in the West: Unappreciated gifts. Materialism. Conflicts over money or property.", "https://i.imgur.com/k14Tt2y.jpg"],
                ["[REVERSED] 2 of Stones - Harmony: Disharmony. A time for solitude.", "https://i.imgur.com/ZlGDL0O.jpg"],
                ["[REVERSED] 3 of Stones - Work: Work not going well. Unemployment. Laziness.", "https://i.imgur.com/MtCBamG.jpg"],
                ["[REVERSED] 4 of Stones - The Power of the Earth: Closing a sense of place. Fear.", "https://i.imgur.com/yp4oZuk.jpg"],
                ["[REVERSED] 5 of Stones - Material Difficulty: Movement for the better. Wait, act cautiously.", "https://i.imgur.com/8pr4ESK.jpg"],
                ["[REVERSED] 6 of Stones - Success: Moment beginning to end. Save or invest money carefully during prosperity.", "https://i.imgur.com/PPETHib.jpg"],
                ["[REVERSED] 7 of Stones - Failure: Recovery. Fresh Start.", "https://i.imgur.com/7IFLca8.jpg"],
                ["[REVERSED] 8 of Stones - Knowledge: Lack of moderation. Impatience. Ignorance.", "https://i.imgur.com/hoGrLuD.jpg"],
                ["[REVERSED] 9 of Stones - Material Gain: Misusing material gain. Greed.", "https://i.imgur.com/DMdpuKv.jpg"],
                ["[REVERSED] 10 of Stones - Richness: Delay. Not appreciating material wealth and security.", "https://i.imgur.com/MPPcgbr.jpg"],
                ["[REVERSED] Daughter of Stones in the West (White Buffalo Woman): Difficulty getting across ideas or emotions. Feeling out of place.", "https://i.imgur.com/n1t3HiJ.jpg"],
                ["[REVERSED] Son of Stones in the West (Chief Seattle): Despair. Selfishness leads to feeling lost.", "https://i.imgur.com/iHjfF81.jpg"],
                ["[REVERSED] Mother of Stones in the West (Spider Woman): Difficulty in staying still and appreciating life. Loss of personal center.", "https://i.imgur.com/xZwqibk.jpg"],
                ["[REVERSED] Father of Stones in the West (Old Man): Cold and uncaring. Lack of success. Pain at the suffering of the world.", "https://i.imgur.com/6A2TrTw.jpg"]
				]
